//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPLIS.Libraries.Data.SSOCore.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_HOSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HS_HOSO()
        {
            this.HS_THANHPHANHOSO = new HashSet<HS_THANHPHANHOSO>();
            this.HS_LIENKETTHUADAT = new HashSet<HS_LIENKETTHUADAT>();
            this.HS_LICHSU = new HashSet<HS_LICHSU>();
        }
    
        public string HOSOID { get; set; }
        public string XAID { get; set; }
        public string MAHOSO { get; set; }
        public string MAHOSO_ST { get; set; }
        public string MAHOSO_MB { get; set; }
        public string MAHOSO_TB { get; set; }
        public string MAHOSO_TAM { get; set; }
        public string TENHOSO { get; set; }
        public string SOTODAIDIEN { get; set; }
        public string SOTHUADAIDIEN { get; set; }
        public Nullable<System.DateTime> NGAYHOSO { get; set; }
        public string PHONG { get; set; }
        public string KE { get; set; }
        public string NGAN { get; set; }
        public string HOP { get; set; }
        public string TENHOP { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> DALIENKETCSDL_KG { get; set; }
        public Nullable<bool> DALIENKETCSDL_TT { get; set; }
        public Nullable<System.DateTime> THOIDIEMKHOITAO { get; set; }
        public string NGUOICAPNHATID { get; set; }
        public Nullable<System.DateTime> THOIDIEMCAPNHAT { get; set; }
        public string OID { get; set; }
        public string HOSOTIEPNHANID { get; set; }
    
        public virtual HC_DMKVHC HC_DMKVHC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HS_THANHPHANHOSO> HS_THANHPHANHOSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HS_LIENKETTHUADAT> HS_LIENKETTHUADAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HS_LICHSU> HS_LICHSU { get; set; }
    }
}
