//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPLIS.Libraries.Data.SSOCore.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_TOCHUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HT_TOCHUC()
        {
            this.HT_TOCHUC_NHOMCHUCNANG = new HashSet<HT_TOCHUC_NHOMCHUCNANG>();
            this.HT_TOCHUC_NGUOIDUNG = new HashSet<HT_TOCHUC_NGUOIDUNG>();
            this.HT_TOCHUC1 = new HashSet<HT_TOCHUC>();
            this.HT_XA_TOCHUC = new HashSet<HT_XA_TOCHUC>();
        }
    
        public string TOCHUCID { get; set; }
        public string KHOACHAID { get; set; }
        public string TENTOCHUC { get; set; }
        public string MOTA { get; set; }
        public string THUTUSAPXEP { get; set; }
        public string uId { get; set; }
        public Nullable<System.DateTime> THOIDIEMKHOITAO { get; set; }
        public string NGUOICAPNHATID { get; set; }
        public Nullable<System.DateTime> THOIDIEMCAPNHAT { get; set; }
        public string DONVIHANHCHINHID { get; set; }
        public Nullable<byte> CAPTOCHUC { get; set; }
        public string MATOCHUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_TOCHUC_NHOMCHUCNANG> HT_TOCHUC_NHOMCHUCNANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_TOCHUC_NGUOIDUNG> HT_TOCHUC_NGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_TOCHUC> HT_TOCHUC1 { get; set; }
        public virtual HT_TOCHUC HT_TOCHUC2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_XA_TOCHUC> HT_XA_TOCHUC { get; set; }
    }
}
